RestaurantSystem/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RestaurantSystem.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.SystemName = "Sistema de Cadastro de Restaurantes";
            return View();
        }
    }
}

RestaurantSystem/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataAccess;
using Models.Base;

namespace RestaurantSystem.Controllers
{
    public class MenusController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Menus
        public ActionResult Index()
        {
            var menu = db.Menu.Include(m => m.Restaurant);
            return View(menu.ToList());
        }

        // GET: Menus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menu.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // GET: Menus/Create
        public ActionResult Create()
        {
            ViewBag.RestaurantID = new SelectList(db.Restaurant, "ID", "name");
            return View();
        }

        // POST: Menus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,RestaurantID,foodName,foodPrice")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                db.Menu.Add(menu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.RestaurantID = new SelectList(db.Restaurant, "ID", "name", menu.RestaurantID);
            return View(menu);
        }

        // GET: Menus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menu.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            ViewBag.RestaurantID = new SelectList(db.Restaurant, "ID", "name", menu.RestaurantID);
            return View(menu);
        }

        // POST: Menus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,RestaurantID,foodName,foodPrice")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(menu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.RestaurantID = new SelectList(db.Restaurant, "ID", "name", menu.RestaurantID);
            return View(menu);
        }

        // GET: Menus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menu.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // POST: Menus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Menu menu = db.Menu.Find(id);
            db.Menu.Remove(menu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RestaurantSystem/Controllers/RestaurantsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataAccess;
using Models.Base;

namespace RestaurantSystem.Controllers
{
    public class RestaurantsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Restaurants
        public ActionResult Index(string name)
        {
            if (string.IsNullOrEmpty(name))
            {
                return View(db.Restaurant.ToList());
            }
            else
            {
                return View(db.Restaurant.Where(p => p.name.Contains(name)).ToList());
            }
            
        }

        // GET: Restaurants/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Restaurant restaurant = db.Restaurant.Find(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            return View(restaurant);
        }

        // GET: Restaurants/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Restaurants/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,name")] Restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                db.Restaurant.Add(restaurant);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(restaurant);
        }

        // GET: Restaurants/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Restaurant restaurant = db.Restaurant.Find(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            return View(restaurant);
        }

        // POST: Restaurants/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,name")] Restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                db.Entry(restaurant).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(restaurant);
        }

        // GET: Restaurants/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Restaurant restaurant = db.Restaurant.Find(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            return View(restaurant);
        }

        // POST: Restaurants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Restaurant restaurant = db.Restaurant.Find(id);
            db.Restaurant.Remove(restaurant);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RestaurantSystem/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}
<br />
<div class="row">
    <div class="col-lg-12 text-center">
        <img src="~/Content/img/home.jpg" />
    </div>
</div>

<div class="row">
    <div class="col-lg-12 text-center">
        <br />
        <h3>
            @ViewBag.SystemName
        </h3>
    </div>
</div>

RestaurantSystem/Views/Menus/Create.cshtml
@model Models.Base.Menu

@{
    ViewBag.Title = "Cadastro de Prato";
}

<h2>Cadastro de Prato</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <h4>Dados</h4>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RestaurantID, "Restaurante", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RestaurantID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RestaurantID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.foodName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.foodName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.foodName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.foodPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.foodPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.foodPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <img src="~/Content/img/icons/icon_cancel.png" class="btn-new" />
                <input type="submit" name="cancel" id="cancel" value="Cancelar" class="btn btn-danger" onclick="cancelNew()" />
                <script>
                    function cancelNew(e) {
                        event.preventDefault()
                        location.href = "/Menus"
                    }
                </script>

                <img src="~/Content/img/icons/icon_save.png" class="btn-new" />
                <input type="submit" name="novo" id="novo" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RestaurantSystem/Views/Menus/Delete.cshtml
@model Models.Base.Menu

@{
    ViewBag.Title = "Remover Prato";
}

<h2>Remover Prato</h2>

<h3>Tem certeza que deseja remover este item ?</h3>
<div>
    <hr />
    <h4>Dados</h4>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Restaurant.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Restaurant.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.foodName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.foodName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.foodPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.foodPrice)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <img src="~/Content/img/icons/icon_cancel.png" class="btn-new" />
            <input type="submit" name="cancel" id="cancel" value="Cancelar" class="btn btn-default" onclick="cancelNew()" />
            <script>
                function cancelNew(e) {
                    event.preventDefault()
                    location.href = "/Menusd"
                }
            </script>
            <img src="~/Content/img/icons/icon_remove.png" class="btn-new" />
            <input type="submit" value="Remover" class="btn btn-danger" />
        </div>
    }
</div>

RestaurantSystem/Views/Menus/Edit.cshtml
@model Models.Base.Menu

@{
    ViewBag.Title = "Editar Prato";
}

<h2>Editar Prato</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <h4>Dados</h4>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.RestaurantID, "Restaurante", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RestaurantID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RestaurantID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.foodName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.foodName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.foodName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.foodPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.foodPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.foodPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <img src="~/Content/img/icons/icon_cancel.png" class="btn-new" />
                <input type="submit" name="cancel" id="cancel" value="Cancelar" class="btn btn-danger" onclick="cancelNew()" />
                <script>
                    function cancelNew(e) {
                        event.preventDefault()
                        location.href = "/Menus"
                    }
                </script>

                <img src="~/Content/img/icons/icon_save.png" class="btn-new" />
                <input type="submit" name="novo" id="novo" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RestaurantSystem/Views/Menus/Index.cshtml
@model IEnumerable<Models.Base.Menu>

@{
    ViewBag.Title = "Index";
}

<h2>Pratos</h2>

<p>
    <img src="~/Content/img/icons/icon_new.png" class="btn-new" />
    <input type="submit" name="novo" id="novo" value="Cadastrar novo Prato" class="btn btn-success" onclick="cadastrar()" />
    <script>
        function cadastrar(e) {
            event.preventDefault()
            location.href = "/Menus/Create"
        }
    </script>
</p>
<table class="table">
    <tr>
        <th style="width: 96px;"></th>
        <th>
            @Html.DisplayNameFor(model => model.Restaurant.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.foodName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.foodPrice)
        </th>

    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.ActionLink(" ", "Delete", new { id = item.ID }, new { @class = "btn-delete" })
            @Html.ActionLink(" ", "Edit", new { id = item.ID }, new { @class = "btn-edit" })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Restaurant.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.foodName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.foodPrice)
        </td>
    </tr>
    }

</table>

RestaurantSystem/Views/Restaurants/Create.cshtml
@model Models.Base.Restaurant

@{
    ViewBag.Title = "Cadastro de Restaurante";
}

<h2>Cadastro de Restaurante</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <h4>Dados</h4>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, "Nome do Restaurante", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <img src="~/Content/img/icons/icon_cancel.png" class="btn-new" />
                <input type="submit" name="cancel" id="cancel" value="Cancelar" class="btn btn-danger" onclick="cancelNew()" />
                <script>
                    function cancelNew(e) {
                        event.preventDefault()
                        location.href = "/Restaurants"
                    }
                </script>

                <img src="~/Content/img/icons/icon_save.png" class="btn-new" />
                <input type="submit" name="novo" id="novo" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RestaurantSystem/Views/Restaurants/Delete.cshtml
@model Models.Base.Restaurant

@{
    ViewBag.Title = "Remover Restaurante";
}

<h2>Remover Restaurante</h2>

<h3>Tem certeza que deseja remover este item ?</h3>
<div>
    <h4>Restaurante</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.LabelFor(model => model.name, "Nome do Restaurante")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <img src="~/Content/img/icons/icon_cancel.png" class="btn-new" />
        <input type="submit" name="cancel" id="cancel" value="Cancelar" class="btn btn-default" onclick="cancelNew()" />
        <script>
            function cancelNew(e) {
                event.preventDefault()
                location.href = "/Restaurants"
            }
        </script>
        <img src="~/Content/img/icons/icon_remove.png" class="btn-new" />
        <input type="submit" value="Remover" class="btn btn-danger" />
    </div>
    }
</div>

RestaurantSystem/Views/Restaurants/Edit.cshtml
@model Models.Base.Restaurant

@{
    ViewBag.Title = "Editar Restaurante";
}

<h2>Editar Restaurante</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <h4>Dados</h4>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.name, "Nome do Restaurante", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <img src="~/Content/img/icons/icon_cancel.png" class="btn-new" />
                <input type="submit" name="cancel" id="cancel" value="Cancelar" class="btn btn-danger" onclick="cancelNew()" />
                <script>
                    function cancelNew(e) {
                        event.preventDefault()
                        location.href = "/Restaurants"
                    }
                </script>

                <img src="~/Content/img/icons/icon_save.png" class="btn-new" />
                <input type="submit" name="novo" id="novo" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RestaurantSystem/Views/Restaurants/Index.cshtml
@model IEnumerable<Models.Base.Restaurant>

@{
    ViewBag.Title = "Restaurantes";
}

<h2>Restaurantes</h2>

@using (Html.BeginForm("Index", "Restaurants", FormMethod.Get))
{
    <div class="row">

        <div class="panel">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title">Filtros</h2>
                </div>
                <div class="panel-body">
                    <div class="form-group row">
                        <div class="col-md-12">
                            <label>Nome: </label>
                            @Html.TextBox("name", ViewBag.CurrentFilter as string, htmlAttributes: new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <img src="~/Content/img/icons/icon_search.png" class="btn-search" />
                            <input type="submit" name="pesquisar" id="pesquisar" value="Pesquisar" class="btn btn-primary" />
                            <img src="~/Content/img/icons/icon_new.png" class="btn-new" />
                            <input type="submit" name="novo" id="novo" value="Cadastrar novo Restaurante" class="btn btn-success" onclick="cadastrar()"/>
                            <script>
                                function cadastrar(e) {
                                    event.preventDefault()
                                    location.href = "/Restaurants/Create"
                                }
                            </script>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<table class="table">
    <tr>
        <th style="width: 96px;"></th>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(" ", "Delete", new { id = item.ID }, new { @class = "btn-delete" })
                @Html.ActionLink(" ", "Edit", new { id = item.ID }, new { @class = "btn-edit" })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
        </tr>
    }

</table>

RestaurantSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Restaurant System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Restaurantes", "Index", "Restaurants")</li>
                    <li>@Html.ActionLink("Pratos", "Index", "Menus")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Rodrigo Mendes</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>